site_name: upq Documentation
site_description: Coroutine-friendly PostgreSQL client and connection pool for uvent
site_url: https://usub-development.github.io/upq/
repo_url: https://github.com/Usub-development/upq
repo_name: Usub-development/upq
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - content.code.copy

plugins:
  - search
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - attr_list
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Connection Pool: pool.md
  - Transactions: transaction.md
  - Query Result: results.md
  - Notifications (LISTEN / NOTIFY): notifications.md
  - Notification Multiplexer: notification-multiplexer.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Usub-development/upq
      name: GitHub Repository
    - icon: fontawesome/solid/star
      link: https://github.com/Usub-development/upq/stargazers
      name: Star on GitHub

copyright: >
  Copyright © 2025 Usub-development, Kirill Zhukov (g2px1)